"""Dynamic msgspec output models and their JSON schema.

Why the model is generated at runtime rather than declared statically:

The output contract is *data-dependent*. Its shape is determined by the specific
questions in each call, which are not known until request time:

- The top-level property names are the caller's question IDs.
- A Choice's answer must have exactly one property per allowed label (extras forbidden),
  each a probability in ``[0, 1]`` carrying that label's criterion as its description.
- A Score's answer is either an integer in ``[0, n)`` or an ``n``-property probability
  map, where ``n`` is that question's number of rubric levels.

No fixed struct can express "exactly these labels, with these descriptions" for labels
that change on every call, so the struct is built per request with ``msgspec.defstruct``
(the supported runtime-struct factory, msgspec's analogue of ``pydantic.create_model``).

One generated struct then does double duty, which is the reason to generate a struct at
all rather than hand-build a schema dict: :func:`create_raw_output_schema` reads the
JSON schema off it to constrain and prompt the provider, and the client decodes the
reply with ``msgspec.json.decode(text, type=model)`` to validate it and drive the
malformed-output corrective retry with a precise error.
"""

from collections.abc import Mapping
from typing import Annotated, Any, Literal

import msgspec
from msgspec import Meta, defstruct, field
from typesafe_sdk import (
    Choice,
    Noul,
    Questions,
    Score,
)
from typesafe_sdk._schemas.models import Question as WireQuestion

from system_one_adapter._utils.probability_normalization import AnswerMode

Question = Noul | Choice | Score

Probability = Annotated[float, Meta(ge=0, le=1)]

_QUESTION_CLASS_BY_TAG = {"noul": Noul, "choice": Choice, "score": Score}

# Score and Choice questions are only meaningful with at least two outcomes to choose
# between.
_MIN_CRITERIA = 2


def convert_question_collection_to_validated_api_question_models(
    questions: Questions,
) -> dict[str, Question]:
    """Convert a question collection to validated API question models.

    Reject empty collections, convert dictionary questions to API model instances, and
    require at least two criteria for scores and choices.

    :param questions: TypeSafe question collection.
    :return: Questions using API model types.
    """
    if not questions:
        raise ValueError("At least one question is required.")
    # Validate the whole collection in one pass through the tagged wire union, which
    # accepts both API model instances and their dictionary form. (The public union
    # carries a recursive ``JSONValue`` alias msgspec cannot convert directly.)
    validated = msgspec.convert(msgspec.to_builtins(questions), type=dict[str, WireQuestion])
    prepared_questions: dict[str, Question] = {}
    for key, wire_question in validated.items():
        fields = msgspec.to_builtins(wire_question)
        prepared_question = _QUESTION_CLASS_BY_TAG[fields.pop("type")](**fields)
        if isinstance(prepared_question, (Score, Choice)) and len(prepared_question.criteria) < _MIN_CRITERIA:
            raise ValueError("Score and choice questions require at least two criteria.")
        prepared_questions[key] = prepared_question
    return prepared_questions


def create_llm_output_model(
    questions: Mapping[str, Question],
    llm_answer_mode: AnswerMode,
) -> type[msgspec.Struct]:
    """Build the per-request output struct: ``{"answers": {<question id>: <answer>}}``.

    Each question contributes one field to the inner ``answers`` struct, aliased to its
    question ID, whose type is generated by :func:`_create_llm_answer_type_for_question`
    to pin the answer to that question's allowed values. See the module docstring for
    why this is generated per request instead of declared statically.

    :param questions: Prepared questions.
    :param llm_answer_mode: Probability or discrete answer mode.
    :return: Dynamic msgspec output model.
    """
    answer_fields = []
    for index, (question_id, question) in enumerate(questions.items()):
        answer_type = _create_llm_answer_type_for_question(
            index,
            question,
            llm_answer_mode,
        )
        is_probability_map = llm_answer_mode == "probabilities" and isinstance(question, (Choice, Score))
        # Choice and Score probability answers are nested models emitted as `$ref`s.
        # Anthropic's structured output silently discards sibling keywords, which would
        # remove the question and criteria. Keep the reference site bare; the model
        # definition and its concrete properties carry that context instead.
        if not is_probability_map:
            answer_type = Annotated[
                answer_type,
                Meta(
                    description=_build_llm_output_field_description(
                        question,
                        llm_answer_mode,
                    )
                ),
            ]
        answer_fields.append((f"answer_{index}", answer_type, field(name=question_id)))

    answers_model = defstruct(
        "TypeSafeAnswers",
        answer_fields,
        forbid_unknown_fields=True,
    )
    # "Keyed by question ID" invited models to invent an ID and nest every answer under
    # it. Name the properties as fixed instead.
    # Put the description on the definition: strict OpenAI output rejects `$ref`
    # siblings, and Anthropic discards them.
    answers_model.__doc__ = (
        "Exactly one answer per property below. Use these property names verbatim and do not add, rename, or nest them under any other key."
    )
    return defstruct(
        "TypeSafeEvaluation",
        [("answers", answers_model)],
        forbid_unknown_fields=True,
    )


def create_raw_output_schema(output_model: type[msgspec.Struct]) -> dict[str, Any]:
    """Create the self-contained JSON schema for the output model.

    :param output_model: Dynamic model from :func:`create_llm_output_model`.
    :return: JSON schema with the root definition inlined and nested models in `$defs`.
    """
    schema = msgspec.json.schema(output_model)
    definitions = schema["$defs"]
    root = schema["$ref"].rsplit("/", maxsplit=1)[-1]
    root_definition = definitions.pop(root)
    return _sanitize_provider_schema({**root_definition, "$defs": definitions})


# Keywords the native structured-output modes do not accept and that the msgspec struct
# still enforces locally on decode: ``title`` is echoed back by OpenAI as an extra
# property (rejected by the ``extra=forbid`` schema), and Anthropic rejects the numeric
# bound keywords outright. The model is still told the ``[0, 1]`` range through the
# field descriptions and system prompt.
_UNSUPPORTED_SCHEMA_KEYWORDS = frozenset({"title", "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum"})


def _sanitize_provider_schema(value: Any) -> Any:
    if isinstance(value, dict):
        sanitized = {}
        for key, item in value.items():
            if key in _UNSUPPORTED_SCHEMA_KEYWORDS:
                continue
            if key in {"properties", "$defs"}:
                # These mappings contain user-defined names, not schema keywords.
                sanitized[key] = {name: _sanitize_provider_schema(schema) for name, schema in item.items()}
            else:
                sanitized[key] = _sanitize_provider_schema(item)
        return sanitized
    if isinstance(value, list):
        return [_sanitize_provider_schema(item) for item in value]
    return value


def _create_llm_answer_type_for_question(
    index: int,
    question: Question,
    llm_answer_mode: AnswerMode,
) -> Any:
    """Build the answer type that pins one question to its allowed values.

    The type depends on the question's own data (its labels or rubric size), so it is
    generated per question:

    - Noul: ``bool`` (discrete) or a ``[0, 1]`` probability.
    - Score: an integer in ``[0, n)`` (discrete) or a struct with one ``[0, 1]``
      probability property per rubric level.
    - Choice: a ``Literal`` of the exact labels (discrete) or a struct with one
      ``[0, 1]`` probability property per label.

    Each probability-map property is aliased to its label and carries the label's
    criterion as its schema description.
    """
    if isinstance(question, Noul):
        return bool if llm_answer_mode == "discrete" else Probability

    if isinstance(question, Score):
        if llm_answer_mode == "discrete":
            return Annotated[int, Meta(ge=0, lt=len(question.criteria))]
        answers_and_criteria = [(str(score), criterion) for score, criterion in enumerate(question.criteria)]
    else:
        answers = list(question.criteria)
        if llm_answer_mode == "discrete":
            # A Literal built from the question's runtime labels.
            return Literal[tuple(answers)]  # pyrefly: ignore[invalid-literal]
        answers_and_criteria = list(question.criteria.items())

    # Put criteria on their concrete properties so they survive `$ref` transforms.
    probability_fields = [
        (
            f"probability_{answer_index}",
            Annotated[
                Probability,
                Meta(description=_serialize_instruction_value_for_prompt(criterion)),
            ],
            field(name=answer),
        )
        for answer_index, (answer, criterion) in enumerate(answers_and_criteria)
    ]
    probability_map = defstruct(
        f"ProbabilityMap{index}",
        probability_fields,  # pyrefly: ignore[bad-argument-type]
        forbid_unknown_fields=True,
    )
    probability_map.__doc__ = _build_llm_output_question_description(question, llm_answer_mode)
    return probability_map


def _build_llm_output_field_description(
    question: Question,
    llm_answer_mode: AnswerMode,
) -> str:
    description = _build_llm_output_question_description(question, llm_answer_mode)

    if isinstance(question, Score):
        levels = "\n".join(
            f"{score} = {_serialize_instruction_value_for_prompt(criterion)}" for score, criterion in enumerate(question.criteria)
        )
        if llm_answer_mode == "discrete":
            return f"{description}\nScore levels, answer with the integer:\n{levels}"
        return f"{description}\nRequired probability keys:\n{levels}"

    if isinstance(question, Choice):
        choices = "\n".join(
            f"{answer} = {_serialize_instruction_value_for_prompt(criterion)}" for answer, criterion in question.criteria.items()
        )
        if llm_answer_mode == "discrete":
            return f"{description}\nChoice labels, answer with one label:\n{choices}"
        return f"{description}\nRequired probability keys:\n{choices}"

    if not isinstance(question, Noul) or question.criteria is None:
        return description

    true_criteria = _serialize_instruction_value_for_prompt(question.criteria.get("true"))
    false_criteria = _serialize_instruction_value_for_prompt(question.criteria.get("false"))
    return f"{description}\nTrue criteria: {true_criteria}\nFalse criteria: {false_criteria}"


def _build_llm_output_question_description(
    question: Question,
    llm_answer_mode: AnswerMode,
) -> str:
    description = _serialize_instruction_value_for_prompt(question.instructions)
    if isinstance(question, Noul) and llm_answer_mode == "probabilities":
        description = (
            "Probability that the answer is yes or the assertion is true. "
            "0 means no or false, 0.5 means uncertain, and 1 means yes or true.\n"
            f"Question: {description}"
        )
    elif isinstance(question, Score) and llm_answer_mode == "probabilities":
        description = f"Each property maps a rubric level to the probability that the document matches it.\nQuestion: {description}"
    elif isinstance(question, Choice) and llm_answer_mode == "probabilities":
        description = f"Each property maps an option to the probability that it is the best answer.\nQuestion: {description}"
    return description


def _serialize_instruction_value_for_prompt(value: Any) -> str:
    if value is None:
        return "No additional instructions."
    if isinstance(value, str):
        return value
    return msgspec.json.encode(value, order="sorted").decode()
